title: Shijie Chang 常世杰
logo: /assets/id.png
description: MSc. Student
department: School of Information and Communication Engineering
organization: Dalian University of Technology
email: csj@mail.dlut.edu.cn
# google_scholar: https://scholar.google.com/citations?user=BlfdYL0AAAAJ
# google_analytics: UA-180788274-1
theme: jekyll-theme-primer
repository: DUT-CSJ/DUT-CSJ.github.io
private: True
