title: Yuchen Fan 范雨晨
logo: /assets/id.png
description: Ph.D. Candidate
department: Department of Electrical and Computer Engineering
organization: University of Illinois at Urbana-Champaign
email: yuchenf4 [at] illinois [dot] edu
google_scholar: https://scholar.google.com/citations?user=BlfdYL0AAAAJ
google_analytics: UA-180788274-1
theme: jekyll-theme-primer
repository: ychfan/ychfan.github.io
private: true